### ISSUE TITLE
Erro Package com.RNTextInputMaskPackage

### ISSUE THREAD

**Issue by pedrogyn** [react-native-community/react-native-text-input-mask#10]
Olá, encontrei o seguinte erro: 
error: package com.RNTextInputMask does not exist import com.RNTextInputMask.RNTextInputMaskPackage;

![scene 1](https://user-images.githubusercontent.com/20590307/30840583-891de0f8-a24e-11e7-9a1d-a9da20e10abf.PNG)

Para resolver, adicionei a seguinte linha de codigo ao gradle.app e depois recompilei o projeto.

compile project(':react-native-text-input-mask')

![scene2](https://user-images.githubusercontent.com/20590307/30840608-a7dd4f24-a24e-11e7-92da-7621c34b2a28.PNG)

abraço

**Comment by ivanzotov** [comment]
@pedrogyn it looks like you didn't execute link command `react-native link react-native-text-input-mask`, this command automatically adds this line into build.gradle

**Comment by filipecavalc** [comment]
react-native link react-native-text-input-mask is not doing the job. I add manualy on android/app/build.gradle the line of code compile project(':react-native-text-input-mask') inside dependencies { }
