### ISSUE TITLE
SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'InputMask')

### ISSUE THREAD

**Issue by LyhengTep** [react-native-community/react-native-text-input-mask#107]
I have just updated Xcode to version 10.2, then it shows (SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'InputMask'). could someone help me with this, please?

react-native version:0.56.0
react-native-text-input-mask:0.8.0

**Comment by lyseiha** [comment]
+1 :D

**Comment by hellpirat** [comment]
+1 :)

**Comment by tienzodi** [comment]
I got same issue here. I tried to set swift target to 4.0. But got new issues:
node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask/RNTextInputMask.m:32:32: No known class method for selector 'maskValueWithText:format:'

node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask/RNTextInputMask.m:37:32: No known class method for selector 'unmaskValueWithText:format:'

node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask/RNTextInputMask.m:52:88: No visible @interface for 'MaskedTextFieldDelegate' declares the selector 'initWithFormat:'

node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask/RNTextInputMask.m:54:25: No known instance method for selector 'setListener:'

**Comment by sgd27** [comment]
> I got same issue here. I tried to set swift target to 4.0. But got new issues:
> node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask/RNTextInputMask.m:32:32: No known class method for selector 'maskValueWithText:format:'
> 
> node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask/RNTextInputMask.m:37:32: No known class method for selector 'unmaskValueWithText:format:'
> 
> node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask/RNTextInputMask.m:52:88: No visible @interface for 'MaskedTextFieldDelegate' declares the selector 'initWithFormat:'
> 
> node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask/RNTextInputMask.m:54:25: No known instance method for selector 'setListener:'

turn on Swift 3 @objc Interface, and everything works fine

**Comment by tienzodi** [comment]
> > I got same issue here. I tried to set swift target to 4.0. But got new issues:
> > node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask/RNTextInputMask.m:32:32: No known class method for selector 'maskValueWithText:format:'
> > node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask/RNTextInputMask.m:37:32: No known class method for selector 'unmaskValueWithText:format:'
> > node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask/RNTextInputMask.m:52:88: No visible @interface for 'MaskedTextFieldDelegate' declares the selector 'initWithFormat:'
> > node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask/RNTextInputMask.m:54:25: No known instance method for selector 'setListener:'
> 
> turn on Swift 3 @objc Interface, and everything works fine

It works. Thank you :)

**Comment by trickyc0d3r** [comment]
how i can turn on swift 3 @obc interface? didnt catch =(

**Comment by trickyc0d3r** [comment]
where it's located?

**Comment by TylerNRobertson** [comment]
same issue on my end, where is it located?

**Comment by gdhillon-pbl** [comment]
Just created https://github.com/react-native-community/react-native-text-input-mask/pull/108  for swift 4.2 upgrade.

**Comment by tienzodi** [comment]
> same issue on my end, where is it located?
You can check my screenshot below:
![Screen Shot 2019-03-27 at 10 32 08 AM](https://user-images.githubusercontent.com/21222786/55048741-e08c4780-507b-11e9-859b-1abcbbbb1703.png)

**Comment by haotangio** [comment]
Can someone upgrade and release a new version for this?

**Comment by gdhillon-pbl** [comment]
> Can someone upgrade and release a new version for this?

There is PR https://github.com/react-native-community/react-native-text-input-mask/pull/108

**Comment by haotangio** [comment]
I was able to archive the build but cannot upload to app store as it said that my bundle contain invalid framework

**Comment by antonsivogrivov** [comment]
+1

**Comment by curselolz** [comment]
+1

**Comment by unnamed92** [comment]
+1

**Comment by edxe** [comment]
> I was able to archive the build but cannot upload to app store as it said that my bundle contain invalid framework

@haotangio how did mange to build?

**Comment by johhansantana** [comment]
> You can check my screenshot below:
> ![Screen Shot 2019-03-27 at 10 32 08 AM](https://user-images.githubusercontent.com/21222786/55048741-e08c4780-507b-11e9-859b-1abcbbbb1703.png)

I can't find it in my build settings:
![Screen Shot 2019-03-27 at 1](https://user-images.githubusercontent.com/9933887/55100396-37077f00-5098-11e9-8828-fba679685259.jpg)

**Comment by johhansantana** [comment]
> You can check my screenshot below:
> ![Screen Shot 2019-03-27 at 10 32 08 AM](https://user-images.githubusercontent.com/21222786/55048741-e08c4780-507b-11e9-859b-1abcbbbb1703.png)

I get the same error after trying this.

I also get a warning when I open the project on xcode:
<img width="413" alt="Screen Shot 2019-03-27 at 2 10 12 PM" src="https://user-images.githubusercontent.com/9933887/55101295-26f09f00-509a-11e9-84f4-cbdb78905b11.png">

> The target “InputMask” contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets.
Use Xcode 10.1 to migrate the code to Swift 4.

**Comment by radetsky** [comment]
Set RNInputMask target to Swift 4.0 and Swift3 objc interface to On helped me to run my project.

**Comment by lynnekers** [comment]
Target to Swift 4.0 and Swift3 objc interface is On, now I'm getting this:
![Screen Shot 2019-03-28 at 08 37 46](https://user-images.githubusercontent.com/22202232/55154938-d2e6c880-5134-11e9-8178-6c4b28833d1f.png)

**Comment by hellpirat** [comment]
Does not work for IOS 12.2

```
objc[366]: Swift class extensions and categories on Swift classes are not allowed to have +load methods
(lldb) 
```

**Comment by migue1s** [comment]
Tested after #108 was merged, getting the same error as above.

Environment:
- react-native-text-input-mask@0.9.0
- react-native@0.57.5
- XCode@10.2
- iOS 12.2

Error:

> objc[10216]: Swift class extensions and categories on Swift classes are not allowed to have +load methods

Note: It works as expected on iOS 12.1.

**Comment by migue1s** [comment]
I linked it via manual linking (not cocoapods) and it's generating a runtime exception on startup. I tested using an iPhone 7 simulator and switching between simulator versions. I also tried cleaning the project but it didn't help. What other details would be helpful to you @gdhillon-pbl ?

**Comment by gdhillon-pbl** [comment]
> I linked it via manual linking (not cocoa pods)

I am using cocoa pods, I will re-check with importing in the project. It doesn't make sense that it compiles for 12.1 and not for 12.2.

**Comment by migue1s** [comment]
It compiles targeting both versions but it crashes on startup on 12.2

**Comment by johhansantana** [comment]
any updates?

**Comment by johhansantana** [comment]
oh.. updated from `0.7.0` to `0.9.0` seemed to fix everything.

**Comment by hellpirat** [comment]
Fixed after upgraded to react-native 0.59.3

**Comment by trickyc0d3r** [comment]
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/olegtiulenev/Library/Developer/Xcode/DerivedData/twentyonevek-aakospyxjhkqufcqmfvtdxqbosih/Build/Products/Debug-iphonesimulator/InputMask.framework/InputMask
  Reason: no suitable image found.  Did find:
	/usr/lib/swift/libswiftCore.dylib: mach-o, but not built for iOS simulator

**Comment by trickyc0d3r** [comment]
rn 0.59.4

**Comment by trickyc0d3r** [comment]
react-native-text-input-mask 0.9.0

**Comment by RadoAz** [comment]
> 0.59.3   Not for me(((

**Comment by trickyc0d3r** [comment]
any solutions?

**Comment by ivanzotov** [comment]
Should work in v1.0.0, ping me to reopen the issue please if it doesn't

**Comment by trickyc0d3r** [comment]
@ivanzotov , Ваня, не работает
RN 0.59.4,
plugin version is 1.0.1
Error dyld: Library not loaded: @rpath/libswiftCore.dylib Referenced from: /Users/user0/Library/Developer/Xcode/DerivedData/project/Build/Products/Debug-iphonesimulator/InputMask.framework/InputMask Reason: no suitable image found. Did find: /usr/lib/swift/libswiftCore.dylib: mach-o, but not built for iOS simulator

**Comment by trickyc0d3r** [comment]
Стоп, несовместимости свифта - нету больше, все ок. Проблема с тем, что библиотеку не видит, если пробовать запустить проект на iOS 12.2 iPhone XS Max

**Comment by hellpirat** [comment]
Try to reinstall pods.
```
cd ios && pod install
```

**Comment by ivanzotov** [comment]
@trickyc0d3r let's speak English, please, or write me directly. Reinstalling pods and node_modules might help I guess

**Comment by ivanzotov** [comment]
@trickyc0d3r check that `Embedded Binaries` has a `InputMask.framework`, try to remove and drag and drop it again if it is already there

**Comment by trickyc0d3r** [comment]
@ivanzotov there is no podspec for package =(
@hellpirat - React-NAtive version is 0.59.4 - not necessary for pod install

**Comment by ivanzotov** [comment]
@trickyc0d3r if you have a time we can connect directly and I can help you, then we will write here the solution we found

**Comment by anicolasdc** [comment]
Hi, i found the solution for this problem, its so easy, check it this:
you have to change your swift language version to 4.2 or 5.0
![Captura de Pantalla 2019-06-06 a la(s) 9 09 24 a  m](https://user-images.githubusercontent.com/36165070/59039778-0f245c80-883b-11e9-8eb2-5f12e03f668c.png)

after that, you have to turn on @objc inference (ON)
![Captura de Pantalla 2019-06-06 a la(s) 9 14 15 a  m](https://user-images.githubusercontent.com/36165070/59040090-a1c4fb80-883b-11e9-88de-25139076a4e2.png)
