### ISSUE TITLE
SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'InputMask')

### ISSUE THREAD

**Issue by hbaseline** [react-native-community/react-native-text-input-mask#123]
My build keeps failing with this error: 
```
SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'InputMask')
```

Xcode: 10.1
react-native: 0.59.8
react-native-text-input-mask:  ^1.0.1

Thank you

**Comment by dsznajder** [comment]
@hbaseline 	I'm not sure but this is probably related to your Xcode version:
https://swift.org/blog/swift-5-released/
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2?language=objc

**Comment by hbaseline** [comment]
Upgrading Xcode to `10.2.1` solved the issue. Thank you

**Comment by zvs001** [comment]
I downgraded library to `0.9.0` to get it work on xcode 10.1

**Comment by Yigityakut** [comment]
> I downgraded library to `0.9.0` to get it work on xcode 10.1

I was really happy when I read this comment but it keeps giving the same error.
