### ISSUE TITLE
The SDK Build Tools revision (23.0.1) is too low for project ':react-native-text-input-mask'. Minimum required is 25.0.0

### ISSUE THREAD

**Issue by churcho** [react-native-community/react-native-text-input-mask#13]
Hitting that when building my app

**Comment by ivanzotov** [comment]
@churcho the latest RN version (0.49.1) uses `buildToolsVersion "23.0.1"`, did you change buildToolsVersion manually?

**Comment by ivanzotov** [comment]
@churcho I thought that your build version is 25.0.0 and closed issue, sorry, now I realized what the error about, will try to fix, thanks

**Comment by sibelius** [comment]
try this on your build.gradle

```
ext {
    compileSdkVersion = 25
    buildToolsVersion = '25.0.3'
}

subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}
```

this will make all your dependencies do use your version of buildTools

**Comment by ivanzotov** [comment]
@sibelius thanks

@churcho I close the issue, let me know if the problem still exists
