### ISSUE TITLE
`selectTextOnFocus` broken

### ISSUE THREAD

**Issue by kdawgwilk** [react-native-community/react-native-text-input-mask#131]
# Bug

on iOS the text is not focused at all and on android the selection behavior is very odd and only selects part of the text when using a currenct mask like so `$[9999999].[00]`

## Environment info

React native info output:

```bash
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 1.49 GB / 32.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.1
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
```

Library version: 1.0.1

## Steps To Reproduce

1. Create an instance of `TextInputMask`
2. Pass it props to `autoFocus` & `selectTextOnFocus` & `mask="$[9999999].[00]"`
3. Try to focus input

Describe what you expected to happen:

1. Selecting text when focused works as expected on iOS & Android

**Comment by kdawgwilk** [comment]
This is actually fixed in newer versions 👍

**Comment by valeriik** [comment]
"react-native": "0.63.2" - selectTextOnFocus does not work on Android or IOS
