### ISSUE TITLE
Merge with other textInput component

### ISSUE THREAD

**Issue by alexalannunes** [react-native-community/react-native-text-input-mask#144]
# Feature Request

I would like (or maybe others devs :] ) that this component has floating label (material) or I can merge with a component that apply material floating label with this component (input-mask)

```jsx
<TextInputMask
  {/* floating label */}
  label={"Phone number"}
  refInput={ref => { this.input = ref }}
  onChangeText={(formatted, extracted) => {
    console.log(formatted) // +1 (123) 456-78-90
    console.log(extracted) // 1234567890
  }}
  mask={"+1 ([000]) [000] [00] [00]"}
/>
```

**Comment by iagorm** [comment]
@alexalannunes, this library only wrap the TextInput and manage the value of it, if you want a floating label or any UI change, you should create your own component and manage focus/blur states.

**Comment by alexalannunes** [comment]
Thanks @iagorm
