### ISSUE TITLE
Build Failed on iOS - "React/RCTBridge.h file not found"

### ISSUE THREAD

**Issue by makarkotlov** [react-native-community/react-native-text-input-mask#145]
I completely followed the readme. Firstly I got confused when I found there is `InputMask.framework` and `InputMaskMac.framework` which is missed on the screenshot in readme.
![Снимок экрана 2019-10-24 в 14 54 18](https://user-images.githubusercontent.com/32848434/67483602-d01e6880-f66e-11e9-8f64-b7928da5512d.png)
Then I put `InputMask.framework` in Embedded and turned `Always Embed Swift Standard Libraries` to "Yes" in Build Settings. And then build failed with `React/RCTBridge.h file not found RNTextInputMask.m`.
![Снимок экрана 2019-10-24 в 14 55 32](https://user-images.githubusercontent.com/32848434/67483902-7d917c00-f66f-11e9-9676-d2df49e9a71e.png)
react-native ^0.61.2
react-native-text-input-mask ^1.0.6

**Comment by amitassaraf** [comment]
Same here :(

**Comment by igor-budzin** [comment]
> +1 Same here :( Seems like this library doesn't support React Native 0.60+

What did you use instead react-native-text-input-mask? Maybe do you know another library with the same functionality and support React Native 0.60+?

**Comment by blueberry6401** [comment]
If you want to use this library on RN 0.60+, read this topic https://github.com/react-native-community/react-native-text-input-mask/issues/135

**Comment by makarkotlov** [comment]
> If you want to use this library on RN 0.60+, read this topic #135

Thank you! I have it working following this PR #140 . We certainly need it merged

**Comment by JuanSeBestia** [comment]
Solved :)

**Comment by makarkotlov** [comment]
solved
