### ISSUE TITLE
Drop requirement of `use_frameworks!` for v0.62

### ISSUE THREAD

**Issue by betoharres** [react-native-community/react-native-text-input-mask#155]
# Feature Request
`react-native` v0.62 introduces Flipper as tool for debugging. But Flipper won't work if you have `use_frameworks!` in your `Podfile`([source](https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.62.0/RnDiffApp/ios/Podfile)).

## Why it is needed
To cope with `react-native` upgrades and output better development experience while using this library.

## Possible implementation
No idea, sorry I'm pretty noob in this part.

### Code sample
Any, :(

**Comment by betoharres** [comment]
> Anyone working in a PR for this?

I don't think so :(

**Comment by lucky-xiaohu** [comment]
It is really a problem

**Comment by walterholohan** [comment]
A big problem. A lot of react-native projects don't need to include `useFrameworks!` anymore making this library incompatible with any projects that do not.

**Comment by walterholohan** [comment]
@betoharres I just installed this library in my RN project running 0.62 and did not need to include `useFrameworks!`. However, the library did not auto-link so I had to manually add `pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'` to my podfile.

**Comment by betoharres** [comment]
@walterholohan thanks for that info! Is the basic functionalities working properly? 
If yes, I'll try to upgrade my current project to 0.62 now =]

**Comment by walterholohan** [comment]
Yep I managed to get a text input with the following mask working - `mask="[000]-[000]"`

**Comment by betoharres** [comment]
Closing this issue since I just tested myself in `v0.63.2` and it successfully build for ios by adding `pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'` to `Podfile`

**Comment by dragma** [comment]
> Closing this issue since I just tested myself in `v0.63.2` and it successfully build for ios by adding `pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'` to `Podfile`

Sorry for digging out this old reply, but I'm facing some annoying issues with RN 0.63.4
I obviously wrote that line in the podfile file, but without any success on iOS build (Debug or Release).

```
<unknown>:0: error: module map file '/Users/xxx/Library/Developer/Xcode/DerivedData/Xxx-ccqzdkfuwbimueevwvvqkmhnpsnh/Build/Products/Release-iphoneos/RNInputMask/RNInputMask.modulemap' not found
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/xxx/Library/Developer/Xcode/DerivedData/Xxx-ccqzdkfuwbimueevwvvqkmhnpsnh/Build/Intermediates.noindex/PrecompiledHeaders/Xxx-Bridging-Header-swift_1XH5I4PY38V4O-clang_3D7YXPTG0VSV.pch' for bridging header '/Users/xxx/xxx/xxx/xxx/ios/Xxx-Bridging-Header.h'
```

Does this errors rings any bells ? :)
