### ISSUE TITLE
Backspace not properly removing characters on both iOS and Android

### ISSUE THREAD

**Issue by alexmngn** [react-native-community/react-native-text-input-mask#159]
# Bug report

## Summary

I've just added this module to my project in order to support masks. 
However, I've noticed an issue when I use the backspace on both iOS and Android that the character is not properly erased. 
I'm not sure the issue is due to this library or due to the RedMadRobot/input-mask library. 

I do reproduce this issue on both iOS and Android. 

This is a screen recording of the issue:

![File from iOS](https://user-images.githubusercontent.com/4203845/83159044-78147c80-a0fd-11ea-9ba2-e6bb8454387c.gif)

## Environment info

`react-native info` output:

```bash
SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version: 2.0.0

## Reproducible sample code

Just a regular use of the text input.

```
<TextInput
      placeholder="([000]) [000]-[00]-[00]"
      mask="([000]) [000]-[00]-[00]"
/>
```

**Comment by ps0305** [comment]
@alexmngn : have you found the fix for the issue?

**Comment by jmargenberg** [comment]
@alexmngn I've also encountered this issue. If you've found a fix could you please share it?

**Comment by aneem** [comment]
This issue seem to occur when the formatted text as value instead of actual text.

As specified in the documentation, the library returns two values on `onChangeText` function.
```
onChangeText={(formatted, extracted) => {
    console.log(formatted) // +1 (123) 456-78-90
    console.log(extracted) // 1234567890
  }}
```
When using the `extracted` value, this issue doesnt occur for both ios and android.

**Example Code**
```
const App = (props) => {
  const [value, setValue] = React.useState()

  return <TextInputMask
    placeholder="([000]) [000]-[00]-[00]"
    mask="([000]) [000]-[00]-[00]"
    value={value}
    onChangeText={(formatted, extracted) => {
      setValue(extracted)
    }}
  />
}
```

**Comment by NeerajNegi** [comment]
What if we want to store the formatted text. If this is the case then it won't work with the current way. Is there any fix to use formatted text in both input and state?

**Comment by asfaarahmed** [comment]
> What if we want to store the formatted text. If this is the case then it won't work with the current way. Is there any fix to use formatted text in both input and state?

import React, { Component, useContext } from 'react';
import TextInputMask from 'react-native-text-input-mask';

export default function testClass() {
     const [valueE, setValueE] = React.useState("")
     const [valueF, setValueF] = React.useState("") 

 <TextInputMask
	refInput={ref => { this.input = ref }}
     	onChangeText={(formatted, extracted) => {
       		setValueE(extracted);
                 setValueF(formatted);
	}}
         value={valueE}
          keyboardType={'numeric'}
          mask={"([000]) [000]-[0000]"}
          placeholder="Phone No"
          placeholderTextColor="#525252"
          keyboardType={'numeric'}
 />

//save valueF in db..

**Comment by NeerajNegi** [comment]
It can be done as @asfaarahmed suggested but it's a workaround and not a fix. I think fixing the backspace issue for formatted value is the best way.
