### ISSUE TITLE
(iOS) SIGABRT on device (emulator works fine)

### ISSUE THREAD

**Issue by AlimovSV** [react-native-community/react-native-text-input-mask#19]
```
dyld`__abort_with_payload:
    0x1047c2f14 <+0>:  mov    x16, #0x209
    0x1047c2f18 <+4>:  svc    #0x80
->  0x1047c2f1c <+8>:  b.lo   0x1047c2f34               ; <+32>
    0x1047c2f20 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1047c2f24 <+16>: mov    x29, sp
    0x1047c2f28 <+20>: bl     0x1047c25b0               ; cerror_nocancel
    0x1047c2f2c <+24>: mov    sp, x29
    0x1047c2f30 <+28>: ldp    x29, x30, [sp], #0x10
    0x1047c2f34 <+32>: ret  
```
dyld: Library not loaded: @rpath/InputMask.framework/InputMask
  Referenced from: /var/containers/Bundle/Application/7852D8F9-46F3-4952-B0BF-5CD16AA12084/Test.app/Test
  Reason: image not found
(lldb) 

Create a clean app:
```
react-native init Test
cd Test
yarn add react-native-text-input-mask
react-native link react-native-text-input-mask
open ./ios/Test.xcodeproj
```
... add TextInputMask in App.js and run.

**Comment by ivanzotov** [comment]
@AlimovSV please look at installation part here https://blog.cloudboost.io/text-input-mask-for-react-native-3c04e82843a6, you need to add InputMask.framework into Embedded Binaries

**Comment by AlimovSV** [comment]
@ivanzotov Thank you very much!

**Comment by maksugr** [comment]
I think it is good idea to tip about it in setup section)

**Comment by ivanzotov** [comment]
@maksugr ok will do )

**Comment by Chleba** [comment]
I have same issue, but it work on device but simulator isn't working. My App just crash and log will tell me just 'abort trap 6'. Do anyone had same issue with it please ?

**Comment by freemansion** [comment]
> @AlimovSV please look at installation part here https://blog.cloudboost.io/text-input-mask-for-react-native-3c04e82843a6, you need to add InputMask.framework into Embedded Binaries

Yeah, it always good idea to look into official docs. 
In my case, a trick was to enable build option `Embed Swift Standard Libraries`
![1*j7VdY3g9_Vz6YTki3T17CQ](https://user-images.githubusercontent.com/3519345/58323560-88d94500-7e4e-11e9-823a-8ce5b58df097.png)
