### ISSUE TITLE
Running app after installing this package makes app crash instantly after booting

### ISSUE THREAD

**Issue by lsunsi** [react-native-community/react-native-text-input-mask#23]
No error messages, no nothing. Just crashes and brings me back to home screen. I'm no React Native 0.50.

**Comment by feronetick** [comment]
Try to build project using Xcode, avoid run "react-native run-ios"

**Comment by kirichok** [comment]
I have this issue too (RN 48.3). When I running app from Xcode everything is ok. On RN 50.0 the same result.

**Comment by Chleba** [comment]
Same problem here. On device is everything running just fine, but on emulator it instantly crash with 'abort trap 6'.

**Comment by jchamb** [comment]
Had same crashing issue. Followed iOS installation steps from https://blog.cloudboost.io/text-input-mask-for-react-native-3c04e82843a6 resolved it.

**Comment by deehuey** [comment]
Why wouldn't these instructions be on the README.md ? ^ Thanks

**Comment by ivanzotov** [comment]
@deehuey fixed )

**Comment by igortupini** [comment]
> Had same crashing issue. Followed iOS installation steps from https://blog.cloudboost.io/text-input-mask-for-react-native-3c04e82843a6 resolved it.

This should be on the docs. Solved my issue, thank you!

**Comment by ksetrin** [comment]
My project with RN 0.59.9 was crashed with ios 12.1 and I have been starting to search a solution
The solution is very simple, but I spent a lot of time to find them
The solution is https://stackoverflow.com/a/26949219
The solution can be effected not only for react-native-text-input-mask
