### ISSUE TITLE
Higher order component?

### ISSUE THREAD

**Issue by Noitidart** [react-native-community/react-native-text-input-mask#24]
Hi there,

Is it possible to use this as a higher order component?

I am using this `<TextField>` component - https://github.com/n4kz/react-native-material-textfield

And need to mask them. Is it possible to field component, with your masker?

**Comment by ArmandoAssuncao** [comment]
You can do in the same way that this repo does, but substituting by your component. Just use the functions exported `mask` and` setMask`.

`import { mask, setMask } from 'react-native-text-input-mask'`

**Comment by Noitidart** [comment]
Oh wow no way thank you sir I will try it out. Thanks for leaving this open for me to close!

**Comment by vinbhai4u** [comment]
Hi @Noitidart can u give an example over here for the same?

**Comment by Sergioamjr** [comment]
I didn't found any reference to how can I use `mask` and `setMask` out of `react-native-text-input-mask`. Could you share an example, please?
