### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by luskin** [react-native-community/react-native-text-input-mask#27]
According to the installation README, after installing and linking android "just works", however it is not working for me. Working great on iOS simulator and on iOS device, but when running on both android simulator and android device I get the following error:

```
undefined is not an object (evaluation '_reactNative.NativeModules.RNTextInputMask.mask')
```

See error here:
![img_0144](https://user-images.githubusercontent.com/5702322/33639687-626ee400-d9e1-11e7-920f-22e494360367.JPG)

I have confirmed that in the settings.gradle is the following:

```
include ':react-native-text-input-mask'
project(':react-native-text-input-mask').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-text-input-mask/android')
```

and in the app/build.gradle is the following:

```
compile project(':react-native-text-input-mask')
```

Any help would be greatly appreciated! Really loving this package on iOS, works great.

**Comment by ivanzotov** [comment]
@luskin it seems like you didn't rebuild the project for android, try to rebuild

**Comment by luskin** [comment]
Quite the contrary @ivanzotov. I have cleaned, rebuilt, reinstalled, ran my cleaning command:

`rm -rf node_modules && yarn install && watchman watch-del-all && rm -rf $TMPDIR/react* && npm start --reset-cache`

Nothing seems to get rid of this error... Maybe it's something in React 0.50?

**Comment by rscottcarson** [comment]
I am seeing the same on iOS simulator

**Comment by ivanzotov** [comment]
@luskin I will try to reproduce and fix, thanks for the issue

**Comment by thambt** [comment]
I have the same problem in React native 0.50.2

**Comment by thambt** [comment]
@luskin @rscottcarson  I find solution in this post https://blog.cloudboost.io/text-input-mask-for-react-native-3c04e82843a6.

**Comment by adirzoari** [comment]
@luskin how did you fix it?

**Comment by ivanzotov** [comment]
I'm closing the issue, @luskin let me know if it still doesn't work with the new versions

**Comment by luskin** [comment]
I ended up building my own solution since I couldn't get it to run, thanks for looking into it though. I may try and work it back in later.

**Comment by potasium** [comment]
the same problem. rn 0.54

**Comment by warlock27** [comment]
@luskin Hi I solved that issue by adding adding the following to my .addPackages

import com.RNTextInputMask.RNTextInputMaskPackage;
...
... 
 mReactInstanceManager = ReactInstanceManager.builder()
                .addPackages(getPackages())
}
   private List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
             ...
                new RNTextInputMaskPackage(),
               ....
        );
    }

I hope this helps

**Comment by luskin** [comment]
@warlock27 I just switched back to this package to try your solution and sure enough that worked. @ivanzotov you probably want to put this in the readme under installation as it seems several people are having this issue, sometimes linking doesn't work and it's always good to reiterate the manual installation process for both iOS and Android. Thanks @warlock27 for solving this issue.
