### ISSUE TITLE
onBlur not works in ios

### ISSUE THREAD

**Issue by ArmandoAssuncao** [react-native-community/react-native-text-input-mask#3]
Hi,

I'm trying use the `onBlur` in ios, but the function is not called.

my code:
```
<TextInputMask
  placeholder="Test"
  onBlur={() => console.log('onBlur works??')} // <- this not works
  onChange={() => console.log('onChange works!!')}
  onChangeText={() => console.log('onChangeText works!!')}
  mask={"+1 ([000]) [000] [00] [00]"} // <- if comment this line, the onBlur works
/>
```
In Android works everything :-)

Tested in:
TextInputMask: 0.4.0
React-Native: 0.48.1
xcode: 8.2.1
simulator iphone 6 (not tested in real device)

**Comment by ivanzotov** [comment]
@ArmandoAssuncao thanks for the issue, I will check it

**Comment by edcs** [comment]
I'm having the same issue, though I can't quite figure out what's stopping it from being called :(

**Comment by ivanzotov** [comment]
@ArmandoAssuncao @edcs fixed – https://github.com/react-native-community/react-native-text-input-mask/commit/f07699310120a82dca344974861dba39d9e77cbe

Please update to 0.4.1

**Comment by hjodr** [comment]
Have the same problem in v 2.0.0
Can I fix it somehow?

**Comment by AlexandrDobrovolskiy** [comment]
Same issue
