### ISSUE TITLE
Doesn't compile with RN 0.53.

### ISSUE THREAD

**Issue by leoneparise** [react-native-community/react-native-text-input-mask#34]
My project is not compiling when I upgrade to RN 0.53.0, here is the error:

```
'RCTTextField.h' file not found
#import "RCTTextField.h"
        ^~~~~~~~~~~~~~~~
1 error generated.

** BUILD FAILED **
```

Anyone having this?

**Comment by duyanh2912** [comment]
Same problem here. I think RCTTextField does not exist in RN 0.53

**Comment by hbk671104** [comment]
Any fix upcoming??

**Comment by AndrewIngram** [comment]
It looks like the module was renamed to `RCTUITextField`: https://github.com/facebook/react-native/commit/19a9c5e41da0aa6ee28a54772edcb92daa498561

**Comment by smisaacs** [comment]
+1

**Comment by phiyan** [comment]
+1

**Comment by leoneparise** [comment]
I fixed the compilation issue myself and opened a PR. 

For those who wants to compile against **RN 0.53.**, replace the dependency line to

`"react-native-text-input-mask": "github:leoneparise/react-native-text-input-mask#fix-build-issue-rn-53",`

and run `yarn install`. 
When they merge my PR and update the library, you can switch the version back.

**Comment by MIREX** [comment]
It doesn't compile yet if you are using Cocoapods, I thing, something wrong with Header Search Path

**Comment by ivanzotov** [comment]
@leoneparise thanks for the PR

I tested on RN 0.53.0, please use `0.6.2` version
