### ISSUE TITLE
Android input flicker and backspacing issue

### ISSUE THREAD

**Issue by andrewcroce** [react-native-community/react-native-text-input-mask#35]
Something similar to #11 seems to be still occurring, even with only setting a `defaultValue` and leaving the value uncontrolled.

Backspacing behavior jumps back several characters at a time.

Using:
react 16.0.0
react-native 0.52.0
react-native-text-input-mask 0.5.2
emulator android 6.0 API 23

```
<TextInputMask
  defaultValue={ this.props.value }
  onChangeText={ this.handleChange }
  mask='[0000] - [0000] - [0000] - [0000]' />

...

handleChange = (formattedValue, extractedValue) => {
  // Im not actually modifying the field's state here
}
```
![android-mask](https://user-images.githubusercontent.com/474639/36174161-65c2cf48-10d9-11e8-99ae-9c2f13224194.gif)

**Comment by mozaik1** [comment]
@andrewcroce Hi. You're using it wrong. 
Change ```defaultValue``` to ```value```

**Comment by andrewcroce** [comment]
Thanks @mozaik1 that worked.

**Comment by ivanzotov** [comment]
@mozaik1 thanks for the help
