### ISSUE TITLE
Not working on RN 0.54

### ISSUE THREAD

**Issue by piotrfalba** [react-native-community/react-native-text-input-mask#39]
Library is not working on RN 0.54
> /node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask/RNTextInputMask.m:45:29: Incompatible pointer types initializing 'RCTUITextField *' with an expression of type 'UIView<RCTBackedTextInputViewProtocol> *'

**Comment by Amurmurmur** [comment]
+1

**Comment by leoneparise** [comment]
I have a PR opened to fix this issue. Until then you can use my branch in you `package.json`:
```
{ 
  "dependencies": {
     "react-native-text-input-mask": "github:leoneparise/react-native-text-input-mask#fix-for-rn-54"
  }
}
```

**Comment by Amurmurmur** [comment]
@leoneparise God bless you 👍

**Comment by Amurmurmur** [comment]
@ivanzotov Could you please merge this one 👍 https://github.com/react-native-community/react-native-text-input-mask/pull/38

**Comment by tete7** [comment]
is it merged? still not working for me
