### ISSUE TITLE
"ref" attribute throws an exception

### ISSUE THREAD

**Issue by jorbs** [react-native-community/react-native-text-input-mask#4]
I'm trying to use the following code:

`<TextInputMask
    mask={"[00]/[00]/[0000]"}
    placeholder="DD/MM/YYYY"
    keyboardType="numeric"
    defaultValue={this.state.startDate}
    returnKeyType="next"
    onSubmitEditing={event => this.refs.endDateInput.focus()}
    onChangeText={startDate => this.setState({startDate})}
    style={[Styles.inputTextMd, Styles.searchInputText]} />`

`<TextInputMask
    ref="endDateInput"
    mask={"[00]/[00]/[0000]"}
    placeholder="DD/MM/YYYY"
    keyboardType="numeric"
    defaultValue={this.state.endDate}
    returnKeyType="done"
    onSubmitEditing={event => this.refs.searchButton.press()}
    onChangeText={endDate => this.setState({endDate})}
    style={[Styles.inputTextMd, Styles.searchInputText]} />`

It throws `undefined is not a function (evaluating _this6.refs.endDateInput.focus()`

**Comment by ivanzotov** [comment]
@jorbs thanks for the issue, I will reproduce it and fix

**Comment by ivanzotov** [comment]
@jorbs fixed – https://github.com/react-native-community/react-native-text-input-mask/commit/033423ee6c20ea74dc37dd70c4e8121315c08d2b#diff-168726dbe96b3ce427e7fedce31bb0bcR36

Update to 0.4.2 and use it like this:

```
<TextInputMask
   mask={"[00]/[00]/[0000]"}
   placeholder="DD/MM/YYYY"
   keyboardType="numeric"
   defaultValue={this.state.startDate}
   returnKeyType="next"
   onSubmitEditing={event => this.endDateInput.focus()}
   onChangeText={startDate => this.setState({startDate})}
   style={[Styles.inputTextMd, Styles.searchInputText]}
/>

<TextInputMask
   refInput={ref => { this.endDateInput = ref }}
   mask={"[00]/[00]/[0000]"}
   placeholder="DD/MM/YYYY"
   keyboardType="numeric"
   defaultValue={this.state.endDate}
   returnKeyType="done"
   onSubmitEditing={event => this.refs.searchButton.press()}
   onChangeText={endDate => this.setState({endDate})}
   style={[Styles.inputTextMd, Styles.searchInputText]}
/>
```

**Comment by jorbs** [comment]
Thanks!
