### ISSUE TITLE
RCTSinglelineTextInputView.h file not found (RNTextInputMask.m)

### ISSUE THREAD

**Issue by ppozniak** [react-native-community/react-native-text-input-mask#45]
Hello there.
I've done the steps in the docs, but no luck, my project on iOS won't build

```
#import "RCTSinglelineTextInputView.h"
```
in file RNTextInputMask.m (line 13)

Versions:
    "react-native-text-input-mask": "^0.7.0",
    "react-native": "0.52.x",
    "react": "16.2.0",
Also using react-native-navigation if this matters

**Comment by grsabreu** [comment]
I'm having this also

**Comment by maphongba008** [comment]
Roll back to version 0.5.2 worked for me

**Comment by ivanzotov** [comment]
@ppozniak I tried to build the library for 0.56 RN, seems it works good so I close the issue, if it still happens please let me know to reopen the issue

**Comment by dogukankotan** [comment]
I'm having same issue on 0.58 RN with version 1.0.1. Any updates? I cannot roll back to before versioning 1 because of the Swift conversation of XCode 10.2. Thanks apple.

**Comment by dogukankotan** [comment]
I found the solution. Make sure import of `libRNTextInputMask.a` after the `libRCTText.a`.
😄

Thanks. 
![Ekran Resmi 2019-04-11 11 50 33](https://user-images.githubusercontent.com/10637834/55946994-5b498b00-5c56-11e9-8bb7-46e4cdedb2b8.png)

**Comment by amitassaraf** [comment]
Anyone found a solution?

**Comment by vishaljadav24** [comment]
I'm having same issue.

 "react": "16.0.0-beta.5",
"react-native": "0.51.0",
"react-native-text-input-mask": "^1.0.1"

**Comment by mouthzipper** [comment]
facing the same issue.

**Comment by andrewhartwig** [comment]
Facing the same issue here as well, seems to come up out of no where. Have had no prior build issues but am getting it today randomly with no code changes.

**Comment by yoavapi** [comment]
same issue

**Comment by Asalem1** [comment]
@ivanzotov this seems like a pretty persistent issue. Is there a reason why it's still closed?

**Comment by sudhanshu-kiwi** [comment]
I'm also facing same issue any idea for this.

**Comment by waris117** [comment]
Facing same issue #import <RCTText/RCTSinglelineTextInputView.h> 'RCTText/RCTSinglelineTextInputView.h not found'
Any one found and working solution, please share, i am using version 1.0.4
 "react-native-text-input-mask": "^1.0.4"

**Comment by sudhanshu-kiwi** [comment]
I have resolved my issue by doing the following step.
1. As @dogukankotan mention I found the solution. Make sure import of libRNTextInputMask.a after the libRCTText.a.
2. add InputMask.framework - Go Library in Xcode -> RNTextInputMask.xcodeproj -> Under TARGETS(RNTextInputMask) -> Build Phases -> Link Binary With Libraries.

**Comment by acollazomayer** [comment]
Same here. I am having the same problem. Is working on development but not in production

**Comment by webmasterdragon** [comment]
Same here. Any solution?
