### ISSUE TITLE
Get value input without mask

### ISSUE THREAD

**Issue by ArmandoAssuncao** [react-native-community/react-native-text-input-mask#5]
Hi,

I'm trying get value of the input without mask, but not works.

code:
```
<TextInputMask
  mask={"[000]-[000]"}
  onChangeText={(text) => console.log(text)}
/>
```
the console print "123-456" instead "123456".

how could i make this?

Tested in:
TextInputMask: 0.4.0
React-Native: 0.48.3
simulator Android 6

thanks :-)

**Comment by ivanzotov** [comment]
@ArmandoAssuncao Hi. I'm working on it, will add this feature asap

**Comment by ivanzotov** [comment]
@ArmandoAssuncao fixed – https://github.com/react-native-community/react-native-text-input-mask/commit/a3eef8c9c0f2cf469e8d9407166c32ec99dbd021

Update to 0.5.0 and just use the second argument for `onChangeText` callback, like this:

```
<TextInputMask
  mask={"[000]-[000]"}
  onChangeText={(text, rawValue) => console.log(text, rawValue)}
/>
```
