### ISSUE TITLE
doesn`t show mask when field focused

### ISSUE THREAD

**Issue by AtNovember** [react-native-community/react-native-text-input-mask#60]
mask shown only if i already enter first symbol.
but it neccesery to display mask when field focused

for example, i need enter phone number

`
              <TextInputMask
                placeholder="Your phone"
                onChangeText={(formatted, extracted) => this.handleMaskedField(formatted, extracted)}
                mask={"+7 ([000]) [000] [00] [00]"}
                keyboardType="numeric"
              />
`

in some countries writtings +7 and 8 are equalent, and some users enter first symbol 8,
then they see the mask erase this number, and start to enter again. 

that`s not ux-friendly,

Please add property, which gives a control to show mask on focus or not

**Comment by ivanzotov** [comment]
@AtNovember thank you for the issue. I understand that is not UX friendly, but I just integrated the third part library https://github.com/RedMadRobot/input-mask-ios into RN. Maybe I will rewrite native code to my own in the future, but for now please refer this issue to `input-mask-ios` library.

Thank you for understanding. Спасибо за понимание 😉
