### ISSUE TITLE
Clear() doesn't work on iOS (RN 0.56)

### ISSUE THREAD

**Issue by russelarms** [react-native-community/react-native-text-input-mask#63]
Hi! Clear() method doesn't seem to work. I've already seen this [https://github.com/facebook/react-native/issues/18272](issue), however pure TextInput clear() method works without any problem.
Here's the code:
`<TextInputMask
                            style={{
        flex: 1,
        fontSize: SCREEN.width > 320 ? scale(typography.fontSizes.l) : 16,
        color: colors.contrast,
        textDecorationLine: 'none',
        padding: 12,
        opacity: 1,
    }}
                            refInput={ref => {
                                this.input = ref
                            }}
                            onChangeText={this.onChangeText}
                            keyboardType={'phone-pad'}
                            selectionColor={colors.contrast}
                            placeholder={'Phone number'}
                            placeholderTextColor={colors.whiteGreen2}
                            editable={this.state.editable}
                            value={this.state.phone}
                            returnKeyType='done'
                            onSubmitEditing={this.onNextClick}
                            mask={"[000] [000] [00] [00]"}
                        />`

and

`clearTextInput = () => {
        this.setState({phone: ''}, () => {
            this.focus();
        });
        this.input.clear();
    };`

React-native 0.56.0
react-native-text-input-mask@^0.7.0
Platform: iOS (android is ok)

**Comment by vdlindenmark** [comment]
This is related to react-native and not react-native-text-input-mask.
https://github.com/facebook/react-native/issues/18272

**Comment by russelarms** [comment]
@vdlindenmark Why textinput.clear() works then?

**Comment by vdlindenmark** [comment]
You did say it's not working...?

BTW, there are also problems with setState: https://github.com/facebook/react-native/issues/18874
Maybe that's related!

**Comment by derenebdon** [comment]
I saw the same issue, iOS failed to clear, Android worked, and only for the masked fields, unmasked TextInput worked.  I created a workaround here based on another PR: https://github.com/derenebdon/react-native-text-input-mask#fixClear.  I exposed a clear method that can be called on a ref of the mask component.

**Comment by javi10823** [comment]
here, same issue in iOS, clear() in iOS doesnt work! any solution?

**Comment by romreed** [comment]
Still have this issue. Any changes?

**Comment by vtretyv** [comment]
It's a react native issue tied to textInput. You an either upgrade to 57.1 +, or replace this file locally:
https://raw.githubusercontent.com/facebook/react-native/2307ea60d03edd234511bfe32474c453f30c1693/Libraries/Text/TextInput/RCTBaseTextInputShadowView.m

Here is a thread on a relevant issue:
https://github.com/facebook/react-native/issues/18874

The very last few posts talk about the fix.

**Comment by romreed** [comment]
@vtretyv i have rn 59.8 and still can't clean textInput.

**Comment by ivanzotov** [comment]
fixed in 1.0.6, please try the new version
