### ISSUE TITLE
Setting a testID prop will crash Android

### ISSUE THREAD

**Issue by lfkwtz** [react-native-community/react-native-text-input-mask#65]
Setting a prop of `testID` will cause a hard crash on Android with `java.lang.String cannot be cast to android.text.TextWatcher`

RN 0.55
v0.7.0

**Comment by FabioVerge** [comment]
I have the same error
RN 0.56
v0.8.0

**Comment by danibonilha** [comment]
I have the same problem, as a workaround, since testID doesn't work in Android, I'm 'filtering' the props, and passing testID only to iOS.
```
const TextInputMask = ({ mask, ...props}) => {
  
  const { testID, ...androidInput } = props;
  const inputProps = (Platform.OS === "ios" ? props : androidInput);

  return <TextInputMask mask={mask} {...inputProps} />;
}

**Comment by yoavapi** [comment]
+1

RN 0.54

**Comment by kdawgwilk** [comment]
👍 RN 0.57.7
