### ISSUE TITLE
[Android] Backspacing issue

### ISSUE THREAD

**Issue by madlabman** [react-native-community/react-native-text-input-mask#71]
It doesn't erase sequence of fixed symbols. On GIF below I can erase dash between numbers with two taps of backspace and I cannot erase [space][bracket] sequence at all and get into brackets. On iOS similar code works fine.

![backspace-input-mask](https://user-images.githubusercontent.com/10616301/44704491-865ae200-aaac-11e8-988f-a3127a85a167.gif)

**Comment by madlabman** [comment]
Fixed issue by setting `autocompletion` option to false on line `46` at `RNTextInputMaskModule.java`
See [response for similar issue on Android input mask project](https://github.com/RedMadRobot/input-mask-android/issues/60)

**Comment by Komalov** [comment]
@madlabman have you ever had this kind of problem? https://github.com/react-native-community/react-native-text-input-mask/pull/78#issuecomment-434678906

**Comment by madlabman** [comment]
@Komalov no, I didn't. I use `8` instead of `+7` and it works fine.

**Comment by gutioliveira** [comment]
@madlabman how did you fix this? How did you set autocompletion to false?

**Comment by madlabman** [comment]
@gutioliveira 

> Fixed issue by setting `autocompletion` option to false on line `46` at `RNTextInputMaskModule.java`
> See [response for similar issue on Android input mask project](https://github.com/RedMadRobot/input-mask-android/issues/60)

You can find this file inside library folder in `node_modules`.
