### ISSUE TITLE
Cannot verify iOS app with this library

### ISSUE THREAD

**Issue by hkan** [react-native-community/react-native-text-input-mask#79]
Hey there! Thanks for this great library. It works like a charm. The only issue I'm having is, I cannot verify and upload my app after I added it to my project. The error message I am getting is `Invalid Bundle. The bundle at '{app name redacted}/Frameworks/InputMask.framework' contains disallowed file 'Frameworks'.` and I have no idea what that even means. Tried googling about it but no luck there.

Is this something about this library, or am I missing something?

**Comment by mattklinker** [comment]
I can't find where I found this info now, but I just ran into this today myself and it was finally resolved by changing the build prop 'Always Embed Swift Standard Libraries' to 'No' for *both* the RNTextInputMask project, as well as it's child InputMask project.

**Comment by hkan** [comment]
It worked! Thanks @mattklinker.
