### ISSUE TITLE
Add ',' separator for currency

### ISSUE THREAD

**Issue by tapdancemobile** [react-native-community/react-native-text-input-mask#8]
Hey! Love the library - I was wondering how hard it would be to add a comma separator for the currency input. I understand that this would be more of a dynamic thing, but I'm curious where you would start on adding something like this?

**Comment by ivanzotov** [comment]
@tapdancemobile Hey. I think about formatted input as well and will try to implement it with "Affine masks" (https://github.com/RedMadRobot/input-mask-ios#affine-masks"), but I'm not sure yet it would solve the issue.

Here is a good library for React (https://github.com/s-yadav/react-number-format) that I'd like to implement for RN. Any ideas/pr are welcome :)

**Comment by tapdancemobile** [comment]
@ivanzotov - Thanks! I am currently having trouble working with the masks as they are static and inline currency formatting requires dynamic insertion of the commas. I have a RN solution for inline formatting - my issue is that the input blink and it is not smooth as all the updates are async in RN. That is why I am looking for a native solution...
