### ISSUE TITLE
Would like to be able to use focus()

### ISSUE THREAD

**Issue by jemilox** [react-native-community/react-native-text-input-mask#87]
<TextInput>              
     onSubmitEditing={() => {this.passwordInput.focus(); }}
<TextInput>
<TextInputMask>
      ref={(input) => {this.passwordInput = input; }}
<TextInputMask>

Would like to be able to change fields using focus, so this library would need to implement it as well.

**Comment by kaueDM** [comment]
Try `this.passwordInput.current.input.focus()`

**Comment by jemilox** [comment]
Thank you!  You saved me so much time!  this.passwordInput.input.focus() worked without the current!

**Comment by sarykemmoun** [comment]
For me, `this.phoneInput.input.focus();`
did the work too.

**Comment by gthrm** [comment]
It doesn't seem to work with functional components. How to use this with useRef?

**Comment by hengkx** [comment]
> It doesn't seem to work with functional components. How to use this with useRef?

+1

**Comment by ignaciolopez12** [comment]
not work

**Comment by vasylnahuliak** [comment]
@gthrm @hengkx @ignaciolopez12 

Work with useRef:
` emailFieldRef?.current?.input?.focus();`

**Comment by max-kim** [comment]
> @gthrm @hengkx @ignaciolopez12
> 
> Work with useRef:
> ` emailFieldRef?.current?.input?.focus();`

Works for me. See my code below:
`
const phoneInput = useRef(null);

const onSubmitEmailInput = useCallback(() => {
    phoneInput.current?.input.focus();
  }, []);

return (
  <>
    <TextInput
      onSubmitEditing={onSubmitEmailInput}
    />
    <TextInputMask
      ref={phoneInput}
      mask={'([000]) [000] [00] [00]'}
      returnKeyType={'done'}
      blurOnSubmit={true}
    />
  </>
);
`

**Comment by abdullahbayram** [comment]
I was able to solve by inputRef.current._inputElement.focus()

**Comment by JeffPatricio** [comment]
> I was able to solve by inputRef.current._inputElement.focus(). react-native-masked-text version : 1.13.0

work's for me, thanks!
