### ISSUE TITLE
The expected dylibs are missing from the app’s Framework location

### ISSUE THREAD

**Issue by curselolz** [react-native-community/react-native-text-input-mask#95]
Here's the message while uploading to App Store

> The expected dylibs are missing from the app’s Framework location, such as /Payload/app/Frameworks

`ALWAYS EMBEDED SWIFT LIBRARIES` flag try to set to `YES `and `NO`, nothing help.

**Comment by aaronnunez95** [comment]
Same issue, @curselolz could you solved this?

**Comment by curselolz** [comment]
> Same issue, @curselolz could you solved this?

We use react-native-masked-text instead of this

**Comment by LyhengTep** [comment]
I've encountered the same issue.

**Comment by trickyc0d3r** [comment]
RN 0.59.4, 
plugin version is 1.0.1
Error `dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/olegtiulenev/Library/Developer/Xcode/DerivedData/twentyonevek-aakospyxjhkqufcqmfvtdxqbosih/Build/Products/Debug-iphonesimulator/InputMask.framework/InputMask
  Reason: no suitable image found.  Did find:
	/usr/lib/swift/libswiftCore.dylib: mach-o, but not built for iOS simulator`

**Comment by RageOfJustice** [comment]
I have the same issue as @trickyc0d3r , but only on 11.3 iOS, maybe its on all 11s versions, because 12.2 is working

**Comment by ivanzotov** [comment]
I reproduced this issue, working on it, thank you

**Comment by RyanThomas73** [comment]
> I have the same issue as @trickyc0d3r , but only on 11.3 iOS, maybe its on all 11s versions, because 12.2 is working

I believe its all osx versions prior to 12.2. We get the same error+crash on devices running 12.1.4, but it works for us on 12.2

**Comment by skartik7** [comment]
@ivanzotov I faced the similar issue issue.

dyld: Library not loaded: @rpath/libswiftCore.dylib
Reason: image not found

Did you find the cause & resolution for this issue?

I tried solution provided by @RyanThomas73 but it didn't worked too.

Thanks in advance. Any help will be appreciated.

**Comment by ivanzotov** [comment]
Try the steps described here:
https://github.com/react-native-community/react-native-text-input-mask/issues/117#issuecomment-513812574
